### ISSUE TITLE
Unwanted line breaks after math elements

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#23] opened 2020-09-03 22:02 UTC
It appears the hyphenated puns cause some line-breaking. 

I don't know why I'm surprised, it's what hyphens do; but it makes interpreting those weird puns harder on the reader.

@skiasaurus  Do you have a fix handy?

![Screenshot (7)](https://user-images.githubusercontent.com/56820096/92177747-61d73480-ee41-11ea-9705-62c99111027d.png)

**Comment by draialexis** [comment] 2020-09-03 22:12
I tried using the `\ns` narrow space you cooked up, but to no avail so far.

**Comment by skiasaurus** [comment] 2020-09-04 01:31
First of all, for clarity: this issue is difficult to reproduce because the placement of line breaks varies from browser to browser and depending on font settings. It so happened that I was able to test one instance of this in my Windows browser, but you should checkout `iss23` and try it for yourself.

My commits to `iss23` establish the command `\nbh` to make a Unicode non-breaking hyphen, in much the same way that `\ns` makes a narrow non-breaking space. However, when I tested this solution, I got this:

![Annotation 2020-09-03 212200](https://user-images.githubusercontent.com/5809600/92188871-be2f5980-ee2b-11ea-9dc2-a37ba7240f1f.png)

I'm fairly certain this is an identical issue to one that I noticed before when I was trying to find a solution to #4, where line breaks would be inserted for no apparent reason immediately after in-line math elements. I raised this privately with Michael, and he replied as follows:

> The linebreaks after math elements derive from fundamental restrictions on rendering math in HTML (via the MathJax JavaScript library). So far as I can tell, such blemishes are the price we pay for having pretty math rendering in browsers, though I would of course be grateful to find out that I’m wrong.

In the meantime, I can see arguments both in favor of and against merging `iss23` into `master`: the "con" (and, in my opinion, stronger) argument is that it looks even uglier; the "pro" argument is that it makes it clearer to the reader that the hyphen is placed there by the typesetter (as opposed to by a line-breaking algorithm).

**Comment by draialexis** [comment] 2020-09-04 11:00
I think here, it might make things clearer for the reader if we get rid of these hyphens altogether, _non_?

**Comment by skiasaurus** [comment] 2020-09-05 02:55
No, because that won't necessarily make the unwanted line breaks after `$...$` constructs go away; and if those persist, the parts of the words that currently come after the hyphen will just appear to be separate words (e.g., _"τ tologie"_), which is even worse than either of the hyphenated options. So I think all we can do, really, is try to decide whether it's a lesser evil to have the hyphen immediately before the break, or immediately after.

**Comment by draialexis** [comment] 2020-09-05 03:44
I hear you.

In that case, we may want to go with `iss23`, because of this:

![Screenshot (7)](https://user-images.githubusercontent.com/56820096/92296943-6d5a5680-ef3a-11ea-9224-2e10d3059a71.png)

"π [linebreak] -eds" is unfortunate, but "π- [linebreak] eds" is evil.

**Comment by skiasaurus** [comment] 2020-09-05 05:55
I'm not sure what exactly you're pointing out there. Can you explain?

By the way, I've tried your solution in the branch `iss23-nh`, just to see what happens. Try it in your browser—it actually works for me.

**Comment by draialexis** [comment] 2020-09-05 14:33
> I'm not sure what exactly you're pointing out there. Can you explain?

When you're splitting a word at the end of a line, you want to use hyphens on both sides of the splitting point.

A) _π_-
-_eds_  ✅

B) _π-_
_eds_ ❌

C) _π_
_-eds_ ❌

[ D) _π-eds_ ✅ ]

`( D ) > A > C > B`

In our case, with a special character as the first half of the word, I think we could justify C over B because it's less jarring. The line with the special character is already unusual, so the absence of the expected hyphen doesn't stick out so much.

I see `iss23-nh`, it looks all right. 

Let me apply similar changes to the other puns and test it in a few browsers, I'll let you know how it goes.

**Comment by draialexis** [comment] 2020-09-05 15:39
It looked fine and I merged with the `alex` branch, feel free to check it out.

**Comment by skiasaurus** [comment] 2020-09-05 22:35
I agree that out of the options available to us, omitting the hyphen entirely is the least objectionable.

> When you're splitting a word at the end of a line, you want to use hyphens on both sides of the splitting point.

In my entire life, the only context in which I've _ever_ seen this style is in certain places in a musical score where a multisyllabic word spans multiple systems. I've never, ever seen it in running text.

**Comment by skiasaurus** [comment] 2020-09-05 22:42
An ideal solution would be one in which we used `\nbh` _and_ there were no unwanted line breaks after math elements, so I'm reopening and adding `wontfix`.

**Comment by draialexis** [comment] 2020-09-14 06:38
> I agree that out of the options available to us, omitting the hyphen entirely is the least objectionable.

>>When you're splitting a word at the end of a line, you want to use hyphens on both sides of the splitting point.

> In my entire life, the only context in which I've ever seen this style is in certain places in a musical score where a multisyllabic word spans multiple systems. I've never, ever seen it in running text.

I missed that, sorry. 

I'm surprised, I didn't think it was that exceptionnal. I've never had to use that knowledge after I was done with school tbh, but it's totally a thing in France.

**Comment by skiasaurus** [comment] 2020-09-15 21:33
Huh. The few French books that I have access to here don't seem to use that style. Do you know of, or can you find, a reference or style guide that recommends it?

**Comment by draialexis** [comment] 2020-09-16 01:33
My... brain made it up? 🤯

No, I think I got that from a teacher or a tutor. Maybe I took it for granted and never looked back. Mayyyyybe it's a rule for specific, hyphenated words, and I extrapolated mistakenly.

I may look into it more later on, in which case I'll share my findings.

Anyway, it's not "totally a thing" at all, it turns out. That's going on the list of things I learned about my language while working on this ^^

**Closed** 2024-11-03 22:12 UTC
Labels: wontfix, trivial, aesthetic
